<?php
$ver = array (
  'ver_mcr_stable' => '1.235',
  'ver_mcr_dev' => '2.0b27',
  'ver_launch' => '1.0',
  'ver_sys' => '3.0',
  'wocauth_legacy_availible' => false,
);
/* This file was auto-generated by WoC Engine 3.0S */
?>